// @generated by tools/predicate-registry.mjs from
// schemas/registry/predicate-registry-v1.json. Do not edit by hand: `pnpm verify:contracts` renders
// this file again and rejects any difference.

use super::{
    Cardinality, EdgeDirection, EvidenceLocatorKind, EvidenceRule, MinimumEvidence,
    PredicateDescriptor, PrerequisiteStrength, QualifierKind, QualifierSchema,
};
use crate::{AuthorityClass, EvidenceStrength, MasteryLevel};

/// Version of the predicate registry these constants were rendered from.
pub const PREDICATE_REGISTRY_VERSION: u16 = 1;

/// §38 gates this registry deliberately leaves open.
///
/// The base taxonomy mix is versioned configuration with no default: the
/// registry names predicates and seeds no concept, field, or competency.
pub const OPEN_GATES: [&str; 1] = ["GATE-38-022"];

/// Node types admitted at either end of an edge, from the §7.1 hierarchy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum NodeType {
    /// `UNIVERSITY`.
    University,
    /// `COLLEGE`.
    College,
    /// `DEPARTMENT`.
    Department,
    /// `INSTRUCTOR`.
    Instructor,
    /// `CURRICULUM_VERSION`.
    CurriculumVersion,
    /// `REQUIREMENT_SET`.
    RequirementSet,
    /// `RULE`.
    Rule,
    /// `COURSE`.
    Course,
    /// `COURSE_REVISION`.
    CourseRevision,
    /// `COURSE_OFFERING`.
    CourseOffering,
    /// `LECTURE`.
    Lecture,
    /// `ASSIGNMENT`.
    Assignment,
    /// `ASSESSMENT`.
    Assessment,
    /// `ENROLLMENT`.
    Enrollment,
    /// `FIELD`.
    Field,
    /// `CONCEPT`.
    Concept,
    /// `CONCEPT_SENSE`.
    ConceptSense,
    /// `COMPETENCY`.
    Competency,
    /// `ARTIFACT`.
    Artifact,
    /// `EVIDENCE_ITEM`.
    EvidenceItem,
    /// `CLAIM`.
    Claim,
    /// `USER_DECISION`.
    UserDecision,
    /// `QUESTION`.
    Question,
    /// `REFRAME`.
    Reframe,
    /// `RESOLUTION`.
    Resolution,
    /// `PROJECT`.
    Project,
    /// `REPOSITORY`.
    Repository,
    /// `SNAPSHOT`.
    Snapshot,
    /// `CODE_COMPONENT`.
    CodeComponent,
    /// `SPEC`.
    Spec,
    /// `ADR`.
    Adr,
    /// `ISSUE`.
    Issue,
    /// `INCIDENT`.
    Incident,
    /// `PROJECT_GOAL`.
    ProjectGoal,
    /// `LEARNING_GOAL`.
    LearningGoal,
    /// `ROLE_PROFILE`.
    RoleProfile,
    /// `PLAN_SCENARIO`.
    PlanScenario,
}

impl NodeType {
    /// Every §7.1 node type, in specification order.
    pub const ALL: [Self; 37] = [
        Self::University,
        Self::College,
        Self::Department,
        Self::Instructor,
        Self::CurriculumVersion,
        Self::RequirementSet,
        Self::Rule,
        Self::Course,
        Self::CourseRevision,
        Self::CourseOffering,
        Self::Lecture,
        Self::Assignment,
        Self::Assessment,
        Self::Enrollment,
        Self::Field,
        Self::Concept,
        Self::ConceptSense,
        Self::Competency,
        Self::Artifact,
        Self::EvidenceItem,
        Self::Claim,
        Self::UserDecision,
        Self::Question,
        Self::Reframe,
        Self::Resolution,
        Self::Project,
        Self::Repository,
        Self::Snapshot,
        Self::CodeComponent,
        Self::Spec,
        Self::Adr,
        Self::Issue,
        Self::Incident,
        Self::ProjectGoal,
        Self::LearningGoal,
        Self::RoleProfile,
        Self::PlanScenario,
    ];

    /// Returns the registry spelling of the node type.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::University => "UNIVERSITY",
            Self::College => "COLLEGE",
            Self::Department => "DEPARTMENT",
            Self::Instructor => "INSTRUCTOR",
            Self::CurriculumVersion => "CURRICULUM_VERSION",
            Self::RequirementSet => "REQUIREMENT_SET",
            Self::Rule => "RULE",
            Self::Course => "COURSE",
            Self::CourseRevision => "COURSE_REVISION",
            Self::CourseOffering => "COURSE_OFFERING",
            Self::Lecture => "LECTURE",
            Self::Assignment => "ASSIGNMENT",
            Self::Assessment => "ASSESSMENT",
            Self::Enrollment => "ENROLLMENT",
            Self::Field => "FIELD",
            Self::Concept => "CONCEPT",
            Self::ConceptSense => "CONCEPT_SENSE",
            Self::Competency => "COMPETENCY",
            Self::Artifact => "ARTIFACT",
            Self::EvidenceItem => "EVIDENCE_ITEM",
            Self::Claim => "CLAIM",
            Self::UserDecision => "USER_DECISION",
            Self::Question => "QUESTION",
            Self::Reframe => "REFRAME",
            Self::Resolution => "RESOLUTION",
            Self::Project => "PROJECT",
            Self::Repository => "REPOSITORY",
            Self::Snapshot => "SNAPSHOT",
            Self::CodeComponent => "CODE_COMPONENT",
            Self::Spec => "SPEC",
            Self::Adr => "ADR",
            Self::Issue => "ISSUE",
            Self::Incident => "INCIDENT",
            Self::ProjectGoal => "PROJECT_GOAL",
            Self::LearningGoal => "LEARNING_GOAL",
            Self::RoleProfile => "ROLE_PROFILE",
            Self::PlanScenario => "PLAN_SCENARIO",
        }
    }
}

/// The twenty §7.2 edges, in specification order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum PredicateName {
    /// `REQUIRES`: advanced concept/competency/goal → prerequisite
    Requires,
    /// `BUILDS_ON`: advanced → foundation
    BuildsOn,
    /// `RELATED_TO`: canonical smaller-ID ↔ larger-ID
    RelatedTo,
    /// `USED_IN`: concept → system/technique/context
    UsedIn,
    /// `IMPLEMENTS`: code component/technique → abstraction/concept
    Implements,
    /// `ABSTRACTS`: abstraction/API → lower mechanism/component
    Abstracts,
    /// `SPECIAL_CASE_OF`: specific → general
    SpecialCaseOf,
    /// `DESIGNED_TO_TEACH`: CourseRevision → concept/competency
    DesignedToTeach,
    /// `TAUGHT_IN`: concept → Lecture
    TaughtIn,
    /// `PRACTICED_IN`: concept/competency → Assignment/Practice
    PracticedIn,
    /// `ASSESSED_IN`: concept/competency → AssessmentItem
    AssessedIn,
    /// `APPLIED_IN`: concept/competency → ProjectSnapshot/CodeComponent
    AppliedIn,
    /// `MENTIONED_IN`: concept/term → source segment
    MentionedIn,
    /// `ENABLES_COMPETENCY`: concept → competency
    EnablesCompetency,
    /// `RELEVANT_TO_ROLE`: competency/concept → RoleProfile
    RelevantToRole,
    /// `OBSERVED_IN_PROJECT`: concept → ProjectSnapshot
    ObservedInProject,
    /// `REQUIRED_BY_PROJECT`: concept → ProjectSnapshot/Goal
    RequiredByProject,
    /// `BENEFICIAL_TO_PROJECT`: concept → ProjectSnapshot/Goal
    BeneficialToProject,
    /// `RESOLVES_QUESTION`: EvidenceItem/Decision → Question
    ResolvesQuestion,
    /// `EVIDENCED_BY`: Claim/StateAssertion → EvidenceItem
    EvidencedBy,
}

impl PredicateName {
    /// Every registered predicate, in specification order.
    pub const ALL: [Self; 20] = [
        Self::Requires,
        Self::BuildsOn,
        Self::RelatedTo,
        Self::UsedIn,
        Self::Implements,
        Self::Abstracts,
        Self::SpecialCaseOf,
        Self::DesignedToTeach,
        Self::TaughtIn,
        Self::PracticedIn,
        Self::AssessedIn,
        Self::AppliedIn,
        Self::MentionedIn,
        Self::EnablesCompetency,
        Self::RelevantToRole,
        Self::ObservedInProject,
        Self::RequiredByProject,
        Self::BeneficialToProject,
        Self::ResolvesQuestion,
        Self::EvidencedBy,
    ];

    /// Returns the registry name of the predicate.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Requires => "REQUIRES",
            Self::BuildsOn => "BUILDS_ON",
            Self::RelatedTo => "RELATED_TO",
            Self::UsedIn => "USED_IN",
            Self::Implements => "IMPLEMENTS",
            Self::Abstracts => "ABSTRACTS",
            Self::SpecialCaseOf => "SPECIAL_CASE_OF",
            Self::DesignedToTeach => "DESIGNED_TO_TEACH",
            Self::TaughtIn => "TAUGHT_IN",
            Self::PracticedIn => "PRACTICED_IN",
            Self::AssessedIn => "ASSESSED_IN",
            Self::AppliedIn => "APPLIED_IN",
            Self::MentionedIn => "MENTIONED_IN",
            Self::EnablesCompetency => "ENABLES_COMPETENCY",
            Self::RelevantToRole => "RELEVANT_TO_ROLE",
            Self::ObservedInProject => "OBSERVED_IN_PROJECT",
            Self::RequiredByProject => "REQUIRED_BY_PROJECT",
            Self::BeneficialToProject => "BENEFICIAL_TO_PROJECT",
            Self::ResolvesQuestion => "RESOLVES_QUESTION",
            Self::EvidencedBy => "EVIDENCED_BY",
        }
    }

    /// Resolves a registry name, or `None` when it is not registered.
    #[must_use]
    pub fn parse(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|value| value.as_str() == name)
    }

    /// Returns everything the registry fixes about this predicate.
    #[must_use]
    pub const fn descriptor(self) -> &'static PredicateDescriptor {
        &PREDICATE_REGISTRY[self as usize]
    }
}

/// The registry itself, indexed by [`PredicateName`].
///
/// The layout below is the generator's, not rustfmt's, so that a byte
/// comparison against a fresh render is the whole drift check.
#[rustfmt::skip]
pub const PREDICATE_REGISTRY: [PredicateDescriptor; 20] = [
    PredicateDescriptor {
        name: PredicateName::Requires,
        predicate_id: "graph.requires",
        since_registry_version: 1,
        spec_direction: "advanced concept/competency/goal → prerequisite",
        spec_meaning: "없으면 목표 수행이 신뢰성 있게 막히는 hard/near-hard dependency. 단순 선호는 금지",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency, NodeType::ProjectGoal, NodeType::LearningGoal],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        prerequisite: true,
        strengths: &[PrerequisiteStrength::Hard, PrerequisiteStrength::Strong],
        personal_state_ceiling: None,
        inverse_label: "is prerequisite of",
        qualifiers: &[
            QualifierSchema {
                key: "prerequisite_strength",
                kind: QualifierKind::PrerequisiteStrength,
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[
                (
                    PrerequisiteStrength::Hard,
                    MinimumEvidence {
                        supporting: 2,
                        independent_sources: 2,
                        min_strength: EvidenceStrength::Direct,
                        authority: &[],
                        locator_kinds: &[],
                    },
                ),
            ],
        },
    },
    PredicateDescriptor {
        name: PredicateName::BuildsOn,
        predicate_id: "graph.builds.on",
        since_registry_version: 1,
        spec_direction: "advanced → foundation",
        spec_meaning: "이해를 깊게 하지만 반드시 선행해야 하는 것은 아닐 수 있음; `REQUIRES`와 구분",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        prerequisite: true,
        strengths: &[PrerequisiteStrength::Strong, PrerequisiteStrength::Helpful],
        personal_state_ceiling: None,
        inverse_label: "is built on by",
        qualifiers: &[
            QualifierSchema {
                key: "prerequisite_strength",
                kind: QualifierKind::PrerequisiteStrength,
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Weak,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::RelatedTo,
        predicate_id: "graph.related.to",
        since_registry_version: 1,
        spec_direction: "canonical smaller-ID ↔ larger-ID",
        spec_meaning: "비방향 연관. path engine의 prerequisite로 사용 금지",
        direction: EdgeDirection::UndirectedCanonical,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency, NodeType::Field],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency, NodeType::Field],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is related to",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Weak,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::UsedIn,
        predicate_id: "graph.used.in",
        since_registry_version: 1,
        spec_direction: "concept → system/technique/context",
        spec_meaning: "일반적으로 사용되는 곳. 개인이 적용했다는 증거는 아님",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::CodeComponent, NodeType::Project],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "uses",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::Implements,
        predicate_id: "graph.implements",
        since_registry_version: 1,
        spec_direction: "code component/technique → abstraction/concept",
        spec_meaning: "구체물이 추상 개념을 구현함",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::CodeComponent, NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Concept, NodeType::ConceptSense],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is implemented by",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::Abstracts,
        predicate_id: "graph.abstracts",
        since_registry_version: 1,
        spec_direction: "abstraction/API → lower mechanism/component",
        spec_meaning: "세부를 감추는 계약; 단순 상위 분류가 아님",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::CodeComponent],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::CodeComponent],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is abstracted by",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::SpecialCaseOf,
        predicate_id: "graph.special.case.of",
        since_registry_version: 1,
        spec_direction: "specific → general",
        spec_meaning: "논리적 subtype/specialization",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency, NodeType::Field],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "generalizes",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::DesignedToTeach,
        predicate_id: "graph.designed.to.teach",
        since_registry_version: 1,
        spec_direction: "CourseRevision → concept/competency",
        spec_meaning: "공식 설명·검토된 curriculum 의도",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::CourseRevision],
        object_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is intended to be taught by",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[AuthorityClass::Official, AuthorityClass::Curated],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::TaughtIn,
        predicate_id: "graph.taught.in",
        since_registry_version: 1,
        spec_direction: "concept → Lecture",
        spec_meaning: "실제 특정 강의에서 설명됨. transcript/material evidence 필요",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Lecture],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Exposed),
        inverse_label: "teaches",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Direct,
                authority: &[],
                locator_kinds: &[EvidenceLocatorKind::TranscriptTime, EvidenceLocatorKind::TextBytes, EvidenceLocatorKind::Page],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::PracticedIn,
        predicate_id: "graph.practiced.in",
        since_registry_version: 1,
        spec_direction: "concept/competency → Assignment/Practice",
        spec_meaning: "사용·연습 기회가 있었음; 성공 의미 아님",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        object_types: &[NodeType::Assignment],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Practiced),
        inverse_label: "gives practice in",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::AssessedIn,
        predicate_id: "graph.assessed.in",
        since_registry_version: 1,
        spec_direction: "concept/competency → AssessmentItem",
        spec_meaning: "실제 평가 대상. 성적과 mastery는 별도",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        object_types: &[NodeType::Assessment],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Exposed),
        inverse_label: "assesses",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::AppliedIn,
        predicate_id: "graph.applied.in",
        since_registry_version: 1,
        spec_direction: "concept/competency → ProjectSnapshot/CodeComponent",
        spec_meaning: "사용자의 실전 적용 evidence가 있음",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense, NodeType::Competency],
        object_types: &[NodeType::Snapshot, NodeType::CodeComponent],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Applied),
        inverse_label: "applies",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Direct,
                authority: &[AuthorityClass::UserExplicit, AuthorityClass::DirectObservation],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::MentionedIn,
        predicate_id: "graph.mentioned.in",
        since_registry_version: 1,
        spec_direction: "concept/term → source segment",
        spec_meaning: "언급만 됨; teaching/understanding으로 승격 금지",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::EvidenceItem],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Exposed),
        inverse_label: "mentions",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Weak,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::EnablesCompetency,
        predicate_id: "graph.enables.competency",
        since_registry_version: 1,
        spec_direction: "concept → competency",
        spec_meaning: "수행에 기여. 중요도와 필요/선택 구분 필요",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Competency],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is enabled by",
        qualifiers: &[
            QualifierSchema {
                key: "contribution_importance",
                kind: QualifierKind::Enumeration(&["CRITICAL", "SUBSTANTIAL", "MINOR"]),
                required: true,
            },
            QualifierSchema {
                key: "necessity",
                kind: QualifierKind::Enumeration(&["NECESSARY", "OPTIONAL"]),
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::RelevantToRole,
        predicate_id: "graph.relevant.to.role",
        since_registry_version: 1,
        spec_direction: "competency/concept → RoleProfile",
        spec_meaning: "versioned role bundle에서의 관련성",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Competency, NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::RoleProfile],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "draws on",
        qualifiers: &[
            QualifierSchema {
                key: "role_profile_version",
                kind: QualifierKind::PositiveInteger,
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::ObservedInProject,
        predicate_id: "graph.observed.in.project",
        since_registry_version: 1,
        spec_direction: "concept → ProjectSnapshot",
        spec_meaning: "code/config/test/runtime에서 강한 증거가 있음",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Snapshot],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: Some(MasteryLevel::Applied),
        inverse_label: "shows evidence of",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Direct,
                authority: &[AuthorityClass::DirectObservation, AuthorityClass::DeterministicEngine],
                locator_kinds: &[EvidenceLocatorKind::RepositoryBytes],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::RequiredByProject,
        predicate_id: "graph.required.by.project",
        since_registry_version: 1,
        spec_direction: "concept → ProjectSnapshot/Goal",
        spec_meaning: "현재 안전한 이해·유지·요구 기능에 필요; failure chain 필요",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Snapshot, NodeType::ProjectGoal],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "currently needs",
        qualifiers: &[
            QualifierSchema {
                key: "failure_chain_ref",
                kind: QualifierKind::EntityReference,
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::BeneficialToProject,
        predicate_id: "graph.beneficial.to.project",
        since_registry_version: 1,
        spec_direction: "concept → ProjectSnapshot/Goal",
        spec_meaning: "명시된 trigger가 생길 때 유익; 현재 필수 아님",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Concept, NodeType::ConceptSense],
        object_types: &[NodeType::Snapshot, NodeType::ProjectGoal],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "would benefit from",
        qualifiers: &[
            QualifierSchema {
                key: "trigger_ref",
                kind: QualifierKind::EntityReference,
                required: true,
            },
        ],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 1,
                independent_sources: 1,
                min_strength: EvidenceStrength::Corroborating,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::ResolvesQuestion,
        predicate_id: "graph.resolves.question",
        since_registry_version: 1,
        spec_direction: "EvidenceItem/Decision → Question",
        spec_meaning: "해결 근거. 상태 변경은 사용자 decision과 별도",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::EvidenceItem, NodeType::UserDecision],
        object_types: &[NodeType::Question],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "is resolved by",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 0,
                independent_sources: 0,
                min_strength: EvidenceStrength::Weak,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
    PredicateDescriptor {
        name: PredicateName::EvidencedBy,
        predicate_id: "graph.evidenced.by",
        since_registry_version: 1,
        spec_direction: "Claim/StateAssertion → EvidenceItem",
        spec_meaning: "claim이 의존하는 근거",
        direction: EdgeDirection::Directed,
        cardinality: Cardinality::ManyToMany,
        subject_types: &[NodeType::Claim],
        object_types: &[NodeType::EvidenceItem],
        prerequisite: false,
        strengths: &[],
        personal_state_ceiling: None,
        inverse_label: "supports",
        qualifiers: &[],
        minimum_evidence: EvidenceRule {
            base: MinimumEvidence {
                supporting: 0,
                independent_sources: 0,
                min_strength: EvidenceStrength::Weak,
                authority: &[],
                locator_kinds: &[],
            },
            by_strength: &[],
        },
    },
];
