// @generated by tools/engine-registry.mjs from
// schemas/registry/engine-registry-v1.json. Do not edit by hand: `pnpm verify:contracts` renders
// this file again and rejects any difference.

use super::{EngineDescriptor, EngineLifecycle, HighImpactPath};

/// Version of the engine registry these constants were rendered from.
pub const ENGINE_REGISTRY_VERSION: u16 = 1;

/// Repository-relative root every engine's harness artifacts live under.
pub const HARNESS_ROOT: &str = "testdata/engines";

/// The §28 table row an engine is registered from, quoted verbatim.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpecRow {
    /// The `Engine` cell.
    pub engine: &'static str,
    /// The `입력` cell.
    pub inputs: &'static str,
    /// The `출력` cell.
    pub outputs: &'static str,
    /// The `핵심 불변조건` cell.
    pub invariant: &'static str,
}

/// The twelve §28 engines, in specification order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EngineName {
    /// `GPA`: REQ-28-001.
    Gpa,
    /// `CREDIT_ACCOUNTING`: REQ-28-002.
    CreditAccounting,
    /// `GRADUATION_AUDIT`: REQ-28-003.
    GraduationAudit,
    /// `TIMETABLE`: REQ-28-004.
    Timetable,
    /// `OFFICIAL_PREREQUISITE`: REQ-28-005.
    OfficialPrerequisite,
    /// `EQUIVALENCY`: REQ-28-006.
    Equivalency,
    /// `TRANSCRIPT_COVERAGE`: REQ-28-007.
    TranscriptCoverage,
    /// `ARTIFACT_INTEGRITY`: REQ-28-008.
    ArtifactIntegrity,
    /// `REPOSITORY_DIFF`: REQ-28-009.
    RepositoryDiff,
    /// `OVERRIDE_RESOLVER`: REQ-28-010.
    OverrideResolver,
    /// `PERMISSION_BROKER`: REQ-28-011.
    PermissionBroker,
    /// `RETENTION_DELETION`: REQ-28-012.
    RetentionDeletion,
}

impl EngineName {
    /// Every registered engine, in specification order.
    pub const ALL: [Self; 12] = [
        Self::Gpa,
        Self::CreditAccounting,
        Self::GraduationAudit,
        Self::Timetable,
        Self::OfficialPrerequisite,
        Self::Equivalency,
        Self::TranscriptCoverage,
        Self::ArtifactIntegrity,
        Self::RepositoryDiff,
        Self::OverrideResolver,
        Self::PermissionBroker,
        Self::RetentionDeletion,
    ];

    /// Returns the registry name of the engine.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Gpa => "GPA",
            Self::CreditAccounting => "CREDIT_ACCOUNTING",
            Self::GraduationAudit => "GRADUATION_AUDIT",
            Self::Timetable => "TIMETABLE",
            Self::OfficialPrerequisite => "OFFICIAL_PREREQUISITE",
            Self::Equivalency => "EQUIVALENCY",
            Self::TranscriptCoverage => "TRANSCRIPT_COVERAGE",
            Self::ArtifactIntegrity => "ARTIFACT_INTEGRITY",
            Self::RepositoryDiff => "REPOSITORY_DIFF",
            Self::OverrideResolver => "OVERRIDE_RESOLVER",
            Self::PermissionBroker => "PERMISSION_BROKER",
            Self::RetentionDeletion => "RETENTION_DELETION",
        }
    }

    /// Resolves a registry name, or `None` when it is not registered.
    #[must_use]
    pub fn parse(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|value| value.as_str() == name)
    }

    /// Returns everything the registry fixes about this engine.
    #[must_use]
    pub const fn descriptor(self) -> &'static EngineDescriptor {
        &ENGINE_REGISTRY[self as usize]
    }
}

/// The registry itself, indexed by [`EngineName`].
///
/// The layout below is the generator's, not rustfmt's, so that a byte
/// comparison against a fresh render is the whole drift check.
#[rustfmt::skip]
pub const ENGINE_REGISTRY: [EngineDescriptor; 12] = [
    EngineDescriptor {
        name: EngineName::Gpa,
        engine_id: "engine.gpa",
        requirement_id: "REQ-28-001",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "GPA",
        inputs: "attempt snapshot, grade/repeat policy",
        outputs: "GPA + inclusion proof",
        invariant: "동일 입력·rule hash면 동일 결과",
    },
        high_impact_path: Some(HighImpactPath::Gpa),
        lifecycle: EngineLifecycle::Implemented,
        harness_dir: "gpa",
    },
    EngineDescriptor {
        name: EngineName::CreditAccounting,
        engine_id: "engine.credit.accounting",
        requirement_id: "REQ-28-002",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Credit Accounting",
        inputs: "recognized attempts, category rules",
        outputs: "category totals",
        invariant: "한 학점의 중복 인정 근거 추적",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Implemented,
        harness_dir: "credit_accounting",
    },
    EngineDescriptor {
        name: EngineName::GraduationAudit,
        engine_id: "engine.graduation.audit",
        requirement_id: "REQ-28-003",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Graduation Audit",
        inputs: "profile, transcript, RequirementSet",
        outputs: "proof tree",
        invariant: "unknown을 pass/fail로 강제하지 않음",
    },
        high_impact_path: Some(HighImpactPath::Graduation),
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "graduation_audit",
    },
    EngineDescriptor {
        name: EngineName::Timetable,
        engine_id: "engine.timetable",
        requirement_id: "REQ-28-004",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Timetable",
        inputs: "meeting intervals, exception approvals",
        outputs: "conflicts",
        invariant: "시간대·부분중복·시험시간 분리",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "timetable",
    },
    EngineDescriptor {
        name: EngineName::OfficialPrerequisite,
        engine_id: "engine.official.prerequisite",
        requirement_id: "REQ-28-005",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Official Prerequisite",
        inputs: "catalog rules, attempts",
        outputs: "eligibility",
        invariant: "AI-inferred 선수지식과 분리",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "official_prerequisite",
    },
    EngineDescriptor {
        name: EngineName::Equivalency,
        engine_id: "engine.equivalency",
        requirement_id: "REQ-28-006",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Equivalency",
        inputs: "effective-dated relation, attempts",
        outputs: "substitution proof",
        invariant: "대체 방향·시점 보존",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "equivalency",
    },
    EngineDescriptor {
        name: EngineName::TranscriptCoverage,
        engine_id: "engine.transcript.coverage",
        requirement_id: "REQ-28-007",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Transcript Coverage",
        inputs: "segments, document mapping",
        outputs: "coverage report",
        invariant: "모든 segment가 정확히 한 처리 상태",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Implemented,
        harness_dir: "transcript_coverage",
    },
    EngineDescriptor {
        name: EngineName::ArtifactIntegrity,
        engine_id: "engine.artifact.integrity",
        requirement_id: "REQ-28-008",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Artifact Integrity",
        inputs: "content hash, manifest",
        outputs: "tamper/corruption result",
        invariant: "원본 변경 탐지",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "artifact_integrity",
    },
    EngineDescriptor {
        name: EngineName::RepositoryDiff,
        engine_id: "engine.repository.diff",
        requirement_id: "REQ-28-009",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Repository Diff",
        inputs: "snapshot manifests",
        outputs: "file/symbol/config diff",
        invariant: "analyzer change와 code change 분리",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "repository_diff",
    },
    EngineDescriptor {
        name: EngineName::OverrideResolver,
        engine_id: "engine.override.resolver",
        requirement_id: "REQ-28-010",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Override Resolver",
        inputs: "claim type, source authority, user decision",
        outputs: "active view + conflicts",
        invariant: "AI가 user-confirmed를 덮지 않음",
    },
        high_impact_path: None,
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "override_resolver",
    },
    EngineDescriptor {
        name: EngineName::PermissionBroker,
        engine_id: "engine.permission.broker",
        requirement_id: "REQ-28-011",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Permission Broker",
        inputs: "data class, purpose, destination, consent",
        outputs: "allow/deny + audit",
        invariant: "default deny, scope 최소화",
    },
        high_impact_path: Some(HighImpactPath::Egress),
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "permission_broker",
    },
    EngineDescriptor {
        name: EngineName::RetentionDeletion,
        engine_id: "engine.retention.deletion",
        requirement_id: "REQ-28-012",
        since_registry_version: 1,
        spec_row: SpecRow {
        engine: "Retention/Deletion",
        inputs: "policy, artifacts, derived graph",
        outputs: "deletion plan/result",
        invariant: "derivative와 backup까지 추적",
    },
        high_impact_path: Some(HighImpactPath::Deletion),
        lifecycle: EngineLifecycle::Planned,
        harness_dir: "retention_deletion",
    },
];
